import { test, expect, type Page } from '@playwright/test';
async function login(page: Page, username = 'admin') {
    await page.goto('/login');
    await page.getByLabel('Username', { exact: true }).fill(username);
    await page.getByLabel('Password', { exact: true }).fill('DemoSecure!2026');
    await page.getByRole('button', { name: 'Sign in to workspace' }).click();
    await expect(page.getByRole('heading', { name: 'Security dashboard' })).toBeVisible();
}
test('full SOC demo: analysis, incident, response, alert and audit persistence', async ({ page }) => {
    const errors: string[] = [];
    page.on('pageerror', error => errors.push(error.message));
    await login(page);
    await expect(page.getByText('Academic demo environment.', { exact: false })).toBeVisible();
    await page.getByRole('link', { name: 'Analyze traffic', exact: true }).click();
    await page.getByRole('button', { name: 'DDoS', exact: true }).click();
    await page.getByRole('button', { name: 'Analyze traffic', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'DDoS', exact: true })).toBeVisible();
    await expect(page.getByText('97.4', { exact: false })).toBeVisible();
    await expect(page.getByText('Incident automatically created:', { exact: false })).toBeVisible();
    await page.getByRole('link', { name: 'Investigate & respond' }).click();
    await expect(page).toHaveURL(/\/threats\/\d+$/);
    const threatPath = new URL(page.url()).pathname;
    await page.getByLabel('Response action').selectOption('Block source');
    await page.getByRole('button', { name: 'Record simulated response' }).click();
    await expect(page.getByRole('status')).toContainText('Block source recorded');
    await expect(page.getByText('Simulated / Demo Response: Block source')).toBeVisible();
    await page.getByRole('link', { name: /INC-\d+ →/ }).first().click();
    await page.getByRole('combobox', { name: 'Status', exact: true }).selectOption('Resolved');
    await page.getByLabel('Resolution / investigation notes').fill('Demo source contained. Investigation complete.');
    await page.getByRole('button', { name: 'Save incident' }).click();
    await expect(page.getByRole('status')).toContainText('Incident updated');
    await page.getByRole('link', { name: 'Alerts', exact: true }).click();
    await page.getByRole('button', { name: 'Acknowledge', exact: true }).first().click();
    await expect(page.getByRole('button', { name: 'Acknowledge', exact: true }).first()).toBeEnabled();
    await page.getByRole('link', { name: 'Audit history', exact: true }).click();
    await expect(page.getByRole('cell', { name: 'Block source — simulated response' }).first()).toBeVisible();
    await page.goto(threatPath);
    await expect(page.getByText('Simulated / Demo Response: Block source')).toBeVisible();
    await page.reload();
    await expect(page.getByText('Simulated / Demo Response: Block source')).toBeVisible();
    await page.screenshot({ path: '../docs/threat-detail.png', fullPage: true });
    expect(errors).toEqual([]);
});
test('invalid login, registration and logout', async ({ page }) => {
    await page.goto('/login');
    await page.getByLabel('Username', { exact: true }).fill('admin');
    await page.getByLabel('Password', { exact: true }).fill('wrong-password');
    await page.getByRole('button', { name: 'Sign in to workspace' }).click();
    await expect(page.getByRole('alert')).toContainText('No active account');
    await page.getByRole('button', { name: 'New analyst? Create an account' }).click();
    const username = `demo_${Date.now()}`;
    await page.getByLabel('Username', { exact: true }).fill(username);
    await page.getByLabel('Email', { exact: true }).fill(`${username}@example.test`);
    await page.getByLabel('Password', { exact: true }).fill('DemoSecure!2026');
    await page.getByRole('button', { name: 'Create analyst account' }).click();
    await expect(page.getByText('Account created.', { exact: false })).toBeVisible();
    await page.getByRole('button', { name: 'Sign in to workspace' }).click();
    await expect(page.getByRole('heading', { name: 'Security dashboard' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Users & access' })).toHaveCount(0);
    await page.getByRole('button', { name: 'Sign out' }).click();
    await expect(page.getByRole('heading', { name: 'Welcome back' })).toBeVisible();
    await page.goto('/threats');
    await expect(page).toHaveURL(/\/login$/);
});
test('filters, manual incident grouping, analytics, users and settings', async ({ page }) => {
    await login(page);
    await page.getByRole('link', { name: 'Threats', exact: true }).click();
    await page.getByLabel('Severity filter').selectOption('Critical');
    await page.getByLabel('Threat type filter').selectOption('DDoS');
    await expect(page.getByRole('row').nth(1)).toContainText('DDoS');
    await page.getByLabel('Search IP, type or threat ID…').fill('not-existing');
    await expect(page.getByRole('heading', { name: 'No records yet' })).toBeVisible();
    await page.getByRole('link', { name: 'Incidents', exact: true }).click();
    await page.getByRole('button', { name: 'Create incident', exact: true }).click();
    await page.getByLabel('Incident title').fill('Grouped demo investigation');
    await page.locator('.threat-picker input').nth(0).check();
    await page.locator('.threat-picker input').nth(1).check();
    await page.getByRole('button', { name: 'Create incident', exact: true }).last().click();
    await expect(page.getByRole('heading', { name: /Grouped demo investigation/ })).toBeVisible();
    await expect(page.getByText('2 linked network detections')).toBeVisible();
    await page.getByRole('link', { name: 'Analytics', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Threat analytics' })).toBeVisible();
    await expect(page.getByText('Not evaluated', { exact: true })).toBeVisible();
    await page.getByRole('link', { name: 'Users & access', exact: true }).click();
    await expect(page.getByRole('cell', { name: 'admin', exact: true })).toBeVisible();
    await page.getByRole('link', { name: 'Settings', exact: true }).click();
    await page.getByLabel('Alert polling interval (seconds)').fill('20');
    await page.getByRole('button', { name: 'Save preferences' }).click();
    await expect(page.getByRole('status')).toContainText('Preferences saved.');
    await page.reload();
    await expect(page.getByLabel('Alert polling interval (seconds)')).toHaveValue('20');
    await page.getByLabel('Alert polling interval (seconds)').fill('30');
    await page.getByRole('button', { name: 'Save preferences' }).click();
});
test('API unavailable and expired authentication have usable states', async ({ page }) => {
    await login(page);
    await page.route('**/api/threats/', route => route.abort());
    await page.goto('/threats');
    await expect(page.getByRole('alert')).toContainText('API unavailable');
    await expect(page.getByRole('button', { name: 'Retry', exact: true })).toBeVisible();
    await page.unroute('**/api/threats/');
    await page.getByRole('button', { name: 'Retry', exact: true }).click();
    await expect(page.getByRole('row').nth(1)).toBeVisible();
    await page.route('**/api/auth/refresh/', route => route.fulfill({ status: 401, contentType: 'application/json', body: JSON.stringify({ error: { detail: 'Token is invalid or expired' } }) }));
    await page.route('**/api/auth/profile/', route => route.fulfill({ status: 401, contentType: 'application/json', body: JSON.stringify({ error: { detail: 'Expired access token' } }) }));
    await page.reload();
    await expect(page).toHaveURL(/\/login$/);
    await expect(page.getByRole('alert')).toContainText('session expired');
});
test('successful refresh restores a session after reload', async ({ page }) => {
    await login(page);
    await page.reload();
    await expect(page.getByRole('heading', { name: 'Security dashboard' })).toBeVisible();
    await page.screenshot({ path: '../docs/dashboard-desktop.png', fullPage: true });
});
test('mobile navigation and flow input remain usable without page overflow', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await login(page);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.getByRole('button', { name: 'Open navigation' }).click();
    await page.getByRole('link', { name: 'Threat analysis', exact: false }).click();
    await expect(page.getByRole('heading', { name: 'Threat analysis', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Benign', exact: true }).click();
    await page.getByRole('button', { name: 'Analyze traffic', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Benign', exact: true })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: '../docs/analysis-mobile.png', fullPage: true });
});
