import { useState, type FormEvent } from 'react';
import { Link, useParams, useNavigate } from 'react-router-dom';
import { Plus, ArrowLeft, ArrowUpRight, Layers } from 'lucide-react';
import { useResource } from '../hooks/useResource';
import { useAuth } from '../hooks/useAuth';
import { post, patch } from '../services/api';
import type { Incident, Threat, AuditEvent } from '../types';
import { PageHeading, Panel, Loading, ErrorState, SearchInput, SeverityBadge, Badge, idLabel, formatTime, Empty, ThreatTable } from '../components/UI';
export function Incidents() { const { data, loading, error, reload } = useResource<Incident[]>('/incidents/'); const threats = useResource<Threat[]>('/threats/'); const [search, setSearch] = useState(''), [status, setStatus] = useState(''), [show, setShow] = useState(false), [title, setTitle] = useState(''), [selected, setSelected] = useState<number[]>([]), [busy, setBusy] = useState(false), [formError, setFormError] = useState(''); const navigate = useNavigate(); async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setFormError(''); try {
    const result = await post<Incident>('/incidents/', { title, threat_ids: selected });
    navigate(`/incidents/${result.id}`);
}
catch (e) {
    setFormError(e instanceof Error ? e.message : 'Could not create incident');
}
finally {
    setBusy(false);
} } const filtered = data?.filter(i => (!status || i.status === status) && `${i.title} ${idLabel('INC', i.id)}`.toLowerCase().includes(search.toLowerCase())) || []; return <><PageHeading eyebrow="INCIDENT RESPONSE" title="Incident management" description="Coordinate investigations and track threats through resolution." actions={<button className="btn primary" onClick={() => setShow(v => !v)}><Plus size={16}/>Create incident</button>}/>{error && <ErrorState error={error} retry={reload}/>} {show && <Panel title="New incident" subtitle="Group related threats in a single investigation"><form className="form-panel" onSubmit={submit}><label>Incident title<input required maxLength={160} value={title} onChange={e => setTitle(e.target.value)} placeholder="Describe the investigation"/></label><label>Related threats (select one or more)</label>{threats.error && <ErrorState error={threats.error} retry={threats.reload}/>}<div className="threat-picker">{threats.data?.map(t => <label className="checkbox-label" key={t.id}><input type="checkbox" checked={selected.includes(t.id)} onChange={e => setSelected(s => e.target.checked ? [...s, t.id] : s.filter(id => id !== t.id))}/><span>{idLabel('THR', t.id)} · {t.threat_type} · {t.source_ip}</span></label>)}</div>{formError && <ErrorState error={formError}/>}<button className="btn primary" disabled={busy || !selected.length}>{busy ? 'Creating…' : 'Create incident'}</button></form></Panel>}<div className="incident-summary">{['Open', 'Investigating', 'Contained', 'Resolved'].map(s => <div key={s}><Badge>{s}</Badge><strong>{data?.filter(i => i.status === s).length || 0}</strong></div>)}</div><Panel><div className="filters"><SearchInput value={search} onChange={setSearch} placeholder="Search incidents…"/><select aria-label="Incident status filter" value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option>{['Open', 'Investigating', 'Contained', 'Resolved'].map(s => <option key={s}>{s}</option>)}</select></div>{loading ? <Loading /> : !filtered.length ? <Empty title="No incidents found" message="Create an incident or analyze high-risk traffic with automatic incident creation enabled."/> : <div className="table-scroll"><table><thead><tr><th>Incident</th><th>Severity</th><th>Status</th><th>Analyst</th><th>Threats</th><th>Updated</th><th /></tr></thead><tbody>{filtered.map(i => <tr key={i.id}><td><Link className="threat-link" to={`/incidents/${i.id}`}>{i.title}</Link><div className="muted tiny mono">{idLabel('INC', i.id)}</div></td><td><SeverityBadge severity={i.severity}/></td><td><Badge>{i.status}</Badge></td><td>{i.assigned_analyst}</td><td>{i.threat_ids.length}</td><td className="muted nowrap">{formatTime(i.updated_at)}</td><td><Link className="icon-button" aria-label={`View incident ${i.id}`} to={`/incidents/${i.id}`}><ArrowUpRight size={17}/></Link></td></tr>)}</tbody></table></div>}<div className="table-footer">{filtered.length} incidents</div></Panel></>; }
export function IncidentDetail() { const { id } = useParams(); const { user } = useAuth(); const resource = useResource<Incident>(`/incidents/${id}/`), threats = useResource<Threat[]>('/threats/'), events = useResource<AuditEvent[]>('/audit/'); const [status, setStatus] = useState(''), [resolution, setResolution] = useState<string | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState(''); const inc = resource.data; async function save(assign = false) { setBusy(true); setError(''); setMessage(''); try {
    await patch(`/incidents/${id}/`, assign ? { assigned_to: user?.id } : { status: status || inc?.status, resolution: resolution ?? inc?.resolution });
    await resource.reload();
    await events.reload();
    setMessage(assign ? 'Incident assigned to you.' : 'Incident updated and recorded in audit history.');
}
catch (e) {
    setError(e instanceof Error ? e.message : 'Update failed');
}
finally {
    setBusy(false);
} } return <><Link className="back-link" to="/incidents"><ArrowLeft size={15}/>Back to incidents</Link><PageHeading eyebrow="INCIDENT INVESTIGATION" title={inc ? `${idLabel('INC', inc.id)} · ${inc.title}` : 'Incident details'} description="Coordinate response and document the resolution."/>{resource.error && <ErrorState error={resource.error} retry={resource.reload}/>} {resource.loading ? <Loading /> : inc && <><div className="incident-detail-header"><SeverityBadge severity={inc.severity}/><Badge>{inc.status}</Badge><span className="muted">Assigned to {inc.assigned_analyst}</span><span className="muted">Created {formatTime(inc.created_at)}</span></div><div className="detail-layout"><div><Panel title="Related threats" subtitle={`${inc.threat_ids.length} linked network detections`}>{threats.error ? <ErrorState error={threats.error} retry={threats.reload}/> : threats.loading ? <Loading /> : <ThreatTable threats={threats.data?.filter(t => inc.threat_ids.includes(t.id)) || []}/>}</Panel><Panel title="Incident timeline"><div className="timeline">{events.error ? <ErrorState error={events.error} retry={events.reload}/> : events.data?.filter(a => a.incident === inc.id).map(a => <div key={a.id}><span className="timeline-dot"/><p>{a.action}<small>{formatTime(a.created_at)} · {a.actor_name}</small></p></div>)}</div></Panel></div><Panel title="Manage incident" subtitle="Changes are saved to the audit log"><form className="form-panel" onSubmit={e => { e.preventDefault(); void save(); }}><label>Status<select value={status || inc.status} onChange={e => setStatus(e.target.value)}>{['Open', 'Investigating', 'Contained', 'Resolved'].map(s => <option key={s}>{s}</option>)}</select></label><label>Resolution / investigation notes<textarea rows={5} maxLength={5000} required={(status || inc.status) === 'Resolved'} value={resolution ?? inc.resolution} onChange={e => setResolution(e.target.value)} placeholder="Describe findings and resolution. Required when resolving."/></label>{error && <ErrorState error={error}/>} {message && <div role="status" className="success-state">{message}</div>}<button className="btn primary full" disabled={busy}>{busy ? 'Saving…' : 'Save incident'}</button><button className="btn full" type="button" disabled={busy} onClick={() => void save(true)}>Assign to me</button><div className="method-note"><Layers size={15}/>Contained incident status records workflow progress. Network blocking remains simulated.</div></form></Panel></div></>}</>; }
