import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { Save, ShieldCheck, RefreshCw } from 'lucide-react';
import { useResource } from '../hooks/useResource';
import { useAuth } from '../hooks/useAuth';
import { patch } from '../services/api';
import type { Settings as SettingsType, AuditEvent, User } from '../types';
import { PageHeading, Panel, Loading, ErrorState, Badge, idLabel, formatTime, Empty } from '../components/UI';
export function Settings() { const resource = useResource<SettingsType>('/settings/'); const health = useResource<{
    status: string;
    database: string;
    analysis_mode: string;
}>('/health/'); const { user } = useAuth(); const [polling, setPolling] = useState(30), [auto, setAuto] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(''), [saved, setSaved] = useState(false); useEffect(() => { if (resource.data) {
    setPolling(resource.data.polling_seconds);
    setAuto(resource.data.auto_incident);
} }, [resource.data]); async function save(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); setSaved(false); try {
    await patch('/settings/', { polling_seconds: polling, auto_incident: auto });
    await resource.reload();
    setSaved(true);
}
catch (e) {
    setError(e instanceof Error ? e.message : 'Save failed');
}
finally {
    setBusy(false);
} } return <><PageHeading eyebrow="WORKSPACE CONFIGURATION" title="Settings" description="Manage your analysis workflow and review environment details."/>{resource.error && <ErrorState error={resource.error} retry={resource.reload}/>}<div className="two-columns"><Panel title="Detection workflow" subtitle="Preferences are persisted for your account">{resource.loading ? <Loading /> : <form className="form-panel" onSubmit={save}><label>Alert polling interval (seconds)<input type="number" required min={10} max={300} value={polling} onChange={e => setPolling(Number(e.target.value))}/><small className="muted">Between 10 and 300 seconds</small></label><label className="checkbox-label"><input type="checkbox" checked={auto} onChange={e => setAuto(e.target.checked)}/><span>Automatically create incidents<small>For High and Critical demo detections</small></span></label>{error && <ErrorState error={error}/>} {saved && <div role="status" className="success-state">Preferences saved.</div>}<button className="btn primary" disabled={busy}><Save size={16}/>{busy ? 'Saving…' : 'Save preferences'}</button></form>}</Panel><Panel title="Environment & engine" subtitle="A transparent view of this demonstration"><div className="key-value-list"><div><span>Analysis mode</span><Badge tone="medium">DEMO</Badge></div><div><span>Classifier</span><strong>Deterministic rules</strong></div><div><span>Random Forest / XGBoost</span><strong>Artifacts not supplied</strong></div><div><span>SHAP / LIME</span><strong>Not integrated</strong></div><div><span>Response execution</span><strong>Simulated only</strong></div><div><span>API health</span><strong>{health.data?.status || 'Unavailable'}</strong></div><div><span>Database connection</span><strong>{health.data?.database || 'Unknown'}</strong></div></div>{health.error && <ErrorState error={health.error} retry={health.reload}/>}</Panel><Panel title="Your profile"><div className="key-value-list"><div><span>Name</span><strong>{user?.first_name || user?.username}</strong></div><div><span>Username</span><strong>{user?.username}</strong></div><div><span>Email</span><strong>{user?.email || 'Not provided'}</strong></div><div><span>Role</span><Badge tone="cyan">{user?.role}</Badge></div></div></Panel><Panel title="Session security"><div className="form-panel"><ShieldCheck size={30} className="cyan-text"/><h3>JWT protected workspace</h3><p className="muted">Access tokens expire after 15 minutes and stay in memory. Refresh tokens rotate and expire after 8 hours; the current refresh token is stored for this browser tab. Logout revokes refresh access.</p><p className="muted">Analysts access their own records. Administrators can inspect all workspace records.</p></div></Panel></div></>; }
export function Audit() { const { data, loading, error, reload } = useResource<AuditEvent[]>('/audit/'); return <><PageHeading eyebrow="ACCOUNTABILITY" title="Audit history" description="A persistent trail of analyses, incident updates, acknowledgements, and simulated responses." actions={<button className="btn" onClick={() => void reload()}><RefreshCw size={16}/>Refresh</button>}/>{error && <ErrorState error={error} retry={reload}/>}<Panel>{loading ? <Loading /> : !data?.length ? <Empty title="No audit events" message="Analyze traffic or update an incident to record an event."/> : <div className="table-scroll"><table><thead><tr><th>Event</th><th>Actor</th><th>Related record</th><th>Mode</th><th>Timestamp</th></tr></thead><tbody>{data.map(a => <tr key={a.id}><td>{a.action}</td><td>{a.actor_name}</td><td>{a.threat ? <Link className="cyan-text mono" to={`/threats/${a.threat}`}>{idLabel('THR', a.threat)}</Link> : a.incident ? <Link className="cyan-text mono" to={`/incidents/${a.incident}`}>{idLabel('INC', a.incident)}</Link> : 'Workspace'}</td><td><Badge tone={a.simulated ? 'medium' : 'cyan'}>{a.simulated ? 'Simulated' : 'Application'}</Badge></td><td className="nowrap muted">{formatTime(a.created_at)}</td></tr>)}</tbody></table></div>}</Panel></>; }
export function Users() { const { data, loading, error, reload } = useResource<User[]>('/users/'); return <><PageHeading eyebrow="ADMINISTRATION" title="Users & access" description="View active accounts and their workspace permissions."/>{error && <ErrorState error={error} retry={reload}/>}<Panel>{loading ? <Loading /> : <div className="table-scroll"><table><thead><tr><th>User</th><th>Username</th><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody>{data?.map(u => <tr key={u.id}><td>{u.first_name || u.username}</td><td className="mono">{u.username}</td><td className="muted">{u.email || '—'}</td><td><Badge tone={u.role === 'ADMIN' ? 'purple' : 'cyan'}>{u.role}</Badge></td><td><Badge tone="low">Active</Badge></td></tr>)}</tbody></table></div>}<div className="table-footer">New registrations receive the Security Analyst role. Admin privileges are managed on the backend.</div></Panel></>; }
